spring:
  application:
    name: guide
  profiles:
    default: local
  main:
    allow-circular-references: true
  config:
    import: "classpath:application-secrets.yml"

  devtools:
    livereload:
      enabled: true
    add-properties: true

  output:
    ansi:
      enabled: detect

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor

  servlet:
    multipart:
      max-file-size: 225MB
      max-request-size: 225MB

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jmx:
    enabled: false

  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://localhost:3306/crud_project?characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    #    hibernate.hbm2ddl.auto: update
    hibernate:
      ddl-auto: update

server:
  port: 9090
  servlet:
#    context-path: /${spring.application.name}
    session:
      timeout: 30m
  error:
    path: /error
    whitelabel:
      enabled: false
    include-exception: true

logging:
  pattern:
    console: '%(%d{yyyy-MM-dd HH:mm:ss.SSS} %30.30logger:%-4line) %-5level > %msg\n'
    file: '%(%d{yyyy-MM-dd HH:mm:ss.SSS} %30.30logger:%-4line) %-5level > %msg\n'
  config: classpath:logback-spring.xml
  file:
    max-history: 7
    max-size: 10MB
    path: ${LOGGING_BASE_PATH:/data/log}/${spring.application.name}
  level:
    root: info
    org.springgramework.web: error
    org.springframework.web.filter.CommonsRequestLoggingFilter: error
    #com.klcube.soda.mapper.CommonMapper : debug
